name: Build and deploy Flask app to Azure Web App - Masterzi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive app
        run: zip -r app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Masterzi'  # Change if your App Service name is different
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B43EEA6B7C494752A393E8047D772DD3 }}
          package: app.zip
